#!/usr/bin/env python3
"""
Telsis language translator

main script

Copyright (c) 2021 Vivian Ng
"""
from telsistrans import *

if __name__ == "__main__":
    # execute only if run as a script
    main()